<?php

  namespace app\helpers;

  class FormatHelper
  {
    //Metodo para obtener las divisas
    public static function getCurrencies(){
      return [
        "Common Currencies" => [
          "USD" => "US Dollar–USD",
          "GBP" => "UK Pound Sterling–GBP",
          "CAD" => "Canadian Dollar–CAD",
          "COP" => "Colombian Peso–COP",
          "AUD" => "Australian Dollar–AUD",
          "EUR" => "Euro–EUR",
        ],
        "All Currencies"    => [
          "ALL" => "Albanian Lek",
          "DZD" => "Algerian Dinar–DZD",
          "AOA" => "Angolan Kwanza–AOA",
          "ARS" => "Argentine Peso–ARS",
          "AMD" => "Armenian Dram–AMD",
          "AWG" => "Aruban Florin–AWG",
          "AUD" => "Australian Dollar–AUD",
          "AZN" => "Azerbaijanian Manat–AZN",
          "BSD" => "Bahamian Dollar–BSD",
          "BHD" => "Bahraini Dinar–BHD",
          "BDT" => "Bangladeshi Taka–BDT",
          "BBD" => "Barbadian Dollar–BBD",
          "BYN" => "Belarusian Ruble–BYN",
          "BZD" => "Belize Dollar–BZD",
          "BOB" => "Boliviano–BOB",
          "BWP" => "Botswana Pula–BWP",
          "BRL" => "Brazilian Real–BRL",
          "BND" => "Brunei Dollar–BND",
          "BGN" => "Bulgarian Lev–BGN",
          "KHR" => "Cambodian Riel–KHR",
          "CAD" => "Canadian Dollar–CAD<",
          "CVE" => "Cape Verdean Escudo–CVE",
          "KYD" => "Cayman Islands Dollar–KYD",
          "XAF" => "Central African CFA franc–XAF",
          "XPF" => "CFP franc–XPF",
          "CLP" => "Chilean Peso–CLP",
          "CNY" => "Chinese Renminbi (Yuan)–CNY",
          "COP" => "Colombian Peso–COP",
          "BAM" => "Convertible Marks–BAM<",
          "CRC" => "Costa Rican Colon–CRC",
          "HRK" => "roatian Kuna–HRK",
          "CZK" => "Czech Koruna–CZK",
          "DKK" => "Danish Krone–DKK",
          "DJF" => "Djiboutian Franc–DJF",
          "DOP" => "Dominican Peso–DOP",
          "XCD" => "Eastern Caribbean Dollar–XCD",
          "EGP" => "Egyptian Pound–EGP",
          "EEK" => "Estonian Kroon–EEK",
          "ETB" => "Ethiopian Birr–ETB",
          "EUR" => "Euro–EUR",
          "FJD" => "Fijian Dollar–FJD",
          "GMD" => "Gambian Dalasi–GMD",
          "GEL" => "Georgian Lari–GEL",
          "GHS" => "Ghanaian Cedi–GHS ",
          "GTQ" => "Guatemalan Quetzal–GTQ",
          "HTG" => "Haitian Gourde–HTG",
          "HNL" => "Honduran Lempira–HNL",
          "HKD" => "Hong Kong Dollar–HKD",
          "HUF" => "Hungarian Forint–HUF",
          "ISK" => "Icelandic Krona–ISK",
          "INR" => "Indian Rupee–INR",
          "IDR" => "Indonesian Rupiah–IDR",
          "IRR" => "Iranian Rial–IRR",
          "IQD" => "Iraqi Dinar–IQD",
          "ILS" => "Israeli new Shekel–ILS",
          "JMD" => "Jamaican Dollar–JMD",
          "JPY" => "Japanese Yen–JPY",
          "JOD" => "Jordanian Dinar–JOD",
          "KZT" => "Kazakhstani Tenge–KZT",
          "KES" => "Kenyan Shilling–KES",
          "KRW" => "Korean Won–KRW",
          "KWD" => "Kuwaiti Dinar–KWD",
          "MMR" => "Kyat–MMR",
          "KGS" => "Kyrgyzstani Som–KGS",
          "LAK" => "Lao Kip–LAK",
          "LBP" => "Lebanese Pound–LBP",
          "LRD" => "Liberian Dollar–LRD",
          "LYD" => "Libyan Dinar–LYD",
          "MOP" => "Macao Pataca–MOP",
          "MKD" => "Macedonian Denar–MKD",
          "MGA" => "Malagasy Ariary–MGA",
          "MWK" => "Malawi Kwacha–MWK",
          "MYR" => "Malaysian Ringgit–MYR",
          "MVR" => "Maldivian Rufiyaa–MVR",
          "MTL" => "Maltese Lira–MTL",
          "MUR" => "Mauritian Rupee–MUR",
          "MXN" => "Mexican Peso–MXN",
          "MDL" => "Moldovan Leu–MDL",
          "MNT" => "Mongolian Tugrik–MNT",
          "MAD" => "Moroccan Dirham–MAD",
          "MZN" => "Mozambican Metical–MZN",
          "NPR" => "Nepalese Rupee–NPR",
          "ANG" => "Netherlands Antillean Gulden–ANG",
          "TWD" => "new Taiwan Dollar–TWD",
          "NZD" => "new Zealand Dollar–NZD",
          "NIO" => "Nicaraguan Cordoba Oro–NIO",
          "NGN" => "Nigerian Naira–NGN",
          "NOK" => "Norwegian Krone–NOK",
          "OMR" => "Omani Rial–OMR",
          "PKR" => "Pakistan Rupee–PKR",
          "PAB" => "Panamanian Balboa–PAB",
          "PGK" => "Papua new Guinean Kina–PGK",
          "PYG" => "Paraguay Guarani–PYG",
          "PEN" => "Peruvian Nuevo Sol–PEN",
          "PHP" => "Philippine Peso–PHP",
          "PLN" => "Polish Zloty–PLN",
          "QAR" => "Qatari Rial–QAR",
          "RON" => "Romanian Leu–RON",
          "RUB" => "Russian Ruble–RUB",
          "RUR" => "Russian Ruble–RUR",
          "RWF" => "Rwandan Franc–RWF",
          "SAR" => "Saudi Riyal–SAR",
          "RSD" => "Serbian Dinar–RSD",
          "SLL" => "Sierra Leonean Leone–SLL",
          "SGD" => "Singapore Dollar–SGD",
          "SKK" => "Slovak Koruna–SKK",
          "SIT" => "Slovenian Tolar–SIT",
          "ZAR" => "South African Rand–ZAR",
          "LKR" => "Sri Lankan Rupee–LKR",
          "SDG" => "Sudanese Pound–SDG",
          "SEK" => "Swedish Krona–SEK",
          "CHF" => "Swiss Franc–CHF",
          "SYP" => "Syrian Pound–SYP",
          "TZS" => "Tanzanian Shilling–TZS",
          "THB" => "Thai Baht–THB",
          "TOP" => "Tongan Dollar–TOP",
          "TTD" => "Trinidad Dollar–TTD",
          "TND" => "Tunisian Dinar–TND",
          "TRY" => "Turkish Lira–TRY",
          "AED" => "UAE Dirham–AED",
          "UGX" => "Ugandan Shilling–UGX",
          "GBP" => "UK Pound Sterling–GBP",
          "UAH" => "Ukrainian Hryvnia–UAH",
          "UYU" => "Uruguayan Peso–UYU",
          "USD" => "US Dollar–USD",
          "UZS" => "Uzbekistan Sum–UZS",
          "VEB" => "Venezuelan Bolivar–VEB",
          "VND" => "Vietnamese Dong–VND",
          "XOF" => "West African CFA franc–XOF",
          "YER" => "Yemeni Rial–YER",
          "ZMW" => "Zambian Kwacha–ZMW",
          "ZWD" => "Zimbabwe Dollar–ZWD",
        ],
      ];
    }

    //Metodo para obtener formatos de número por divisa
    public static function getNumberFormats(){
      return [
        "123,456.78"  => "123,456.78",
        "123.456,78"  => "123.456,78",
        "123,456.789" => "123,456.789",
        "123 456.78"  => "123 456.78",
        "123'456.78"  => "123'456.78",
        "123.456"     => "123.456",
        "123,456"     => "123,456",
        "123 456-78"  => "123 456-78",
        "123 456,78"  => "123 456,78",
        "123,456/78"  => "123,456/78",
        "123 456"     => "123 456",
        "1,23,456.78" => "1,23,456.78",

      ];
    }

    //Metodo para  obtener formato de fechas
    public static function getPlacement(){
      return [
        "Symbol First" => "Before amount ($123,456.78)",
        "Symbol Last"  => "After amount (123,456.78$)",
        "Symbol None"  => "Don't show (123,456.78)",
      ];
    }

    //Metodo para  obtener formato de fechas
    public static function getDateFormats(){
      return [
        "YYYY/MM/DD" => "2024/12/30",
        "YYYY-MM-DD" => "2024-12-30",
        "DD-MM-YYYY" => "30-12-2024",
        "DD/MM/YYYY" => "30/12/2024",
        "DD.MM.YYYY" => "30.12.2024",
        "MM/DD/YYYY" => "12/30/2024",
        "YYYY.MM.DD" => "2024.12.30",
      ];
    }

  }

